// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kv.proto

package kvwrappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEventMessage_EventType int32

const (
	WatchEventMessage_SET    WatchEventMessage_EventType = 0
	WatchEventMessage_DELETE WatchEventMessage_EventType = 1
)

// Enum value maps for WatchEventMessage_EventType.
var (
	WatchEventMessage_EventType_name = map[int32]string{
		0: "SET",
		1: "DELETE",
	}
	WatchEventMessage_EventType_value = map[string]int32{
		"SET":    0,
		"DELETE": 1,
	}
)

func (x WatchEventMessage_EventType) Enum() *WatchEventMessage_EventType {
	p := new(WatchEventMessage_EventType)
	*p = x
	return p
}

func (x WatchEventMessage_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventMessage_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (WatchEventMessage_EventType) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x WatchEventMessage_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventMessage_EventType.Descriptor instead.
func (WatchEventMessage_EventType) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9, 0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *SetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

type AllKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"` // Optional prefix filter
	BufferSize    uint32                 `protobuf:"varint,3,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllKeysRequest) Reset() {
	*x = AllKeysRequest{}
	mi := &file_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKeysRequest) ProtoMessage() {}

func (x *AllKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKeysRequest.ProtoReflect.Descriptor instead.
func (*AllKeysRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{6}
}

func (x *AllKeysRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *AllKeysRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *AllKeysRequest) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

type AllKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllKeysResponse) Reset() {
	*x = AllKeysResponse{}
	mi := &file_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKeysResponse) ProtoMessage() {}

func (x *AllKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKeysResponse.ProtoReflect.Descriptor instead.
func (*AllKeysResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{7}
}

func (x *AllKeysResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AllKeysResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	KeyOrPrefix   []byte                 `protobuf:"bytes,2,opt,name=key_or_prefix,json=keyOrPrefix,proto3" json:"key_or_prefix,omitempty"`
	IsPrefix      bool                   `protobuf:"varint,3,opt,name=is_prefix,json=isPrefix,proto3" json:"is_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{8}
}

func (x *WatchRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *WatchRequest) GetKeyOrPrefix() []byte {
	if x != nil {
		return x.KeyOrPrefix
	}
	return nil
}

func (x *WatchRequest) GetIsPrefix() bool {
	if x != nil {
		return x.IsPrefix
	}
	return false
}

type WatchEventMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventType     WatchEventMessage_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=kvwrappb.WatchEventMessage_EventType" json:"event_type,omitempty"`
	Partition     string                      `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                      `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                      `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventMessage) Reset() {
	*x = WatchEventMessage{}
	mi := &file_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventMessage) ProtoMessage() {}

func (x *WatchEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventMessage.ProtoReflect.Descriptor instead.
func (*WatchEventMessage) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9}
}

func (x *WatchEventMessage) GetEventType() WatchEventMessage_EventType {
	if x != nil {
		return x.EventType
	}
	return WatchEventMessage_SET
}

func (x *WatchEventMessage) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *WatchEventMessage) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchEventMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\bkvwrappb\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"2\n" +
	"\vGetResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"R\n" +
	"\n" +
	"SetRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\r\n" +
	"\vSetResponse\"?\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"g\n" +
	"\x0eAllKeysRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\fR\x06prefix\x12\x1f\n" +
	"\vbuffer_size\x18\x03 \x01(\rR\n" +
	"bufferSize\"9\n" +
	"\x0fAllKeysResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"m\n" +
	"\fWatchRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\"\n" +
	"\rkey_or_prefix\x18\x02 \x01(\fR\vkeyOrPrefix\x12\x1b\n" +
	"\tis_prefix\x18\x03 \x01(\bR\bisPrefix\"\xc1\x01\n" +
	"\x11WatchEventMessage\x12D\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2%.kvwrappb.WatchEventMessage.EventTypeR\teventType\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\" \n" +
	"\tEventType\x12\a\n" +
	"\x03SET\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x012\xb2\x02\n" +
	"\tKvService\x122\n" +
	"\x03Get\x12\x14.kvwrappb.GetRequest\x1a\x15.kvwrappb.GetResponse\x122\n" +
	"\x03Set\x12\x14.kvwrappb.SetRequest\x1a\x15.kvwrappb.SetResponse\x12;\n" +
	"\x06Delete\x12\x17.kvwrappb.DeleteRequest\x1a\x18.kvwrappb.DeleteResponse\x12@\n" +
	"\aAllKeys\x12\x18.kvwrappb.AllKeysRequest\x1a\x19.kvwrappb.AllKeysResponse0\x01\x12>\n" +
	"\x05Watch\x12\x16.kvwrappb.WatchRequest\x1a\x1b.kvwrappb.WatchEventMessage0\x01B2Z0github.com/ryebreadgit/kvwrap-client-go/kvwrappbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kv_proto_goTypes = []any{
	(WatchEventMessage_EventType)(0), // 0: kvwrappb.WatchEventMessage.EventType
	(*GetRequest)(nil),               // 1: kvwrappb.GetRequest
	(*GetResponse)(nil),              // 2: kvwrappb.GetResponse
	(*SetRequest)(nil),               // 3: kvwrappb.SetRequest
	(*SetResponse)(nil),              // 4: kvwrappb.SetResponse
	(*DeleteRequest)(nil),            // 5: kvwrappb.DeleteRequest
	(*DeleteResponse)(nil),           // 6: kvwrappb.DeleteResponse
	(*AllKeysRequest)(nil),           // 7: kvwrappb.AllKeysRequest
	(*AllKeysResponse)(nil),          // 8: kvwrappb.AllKeysResponse
	(*WatchRequest)(nil),             // 9: kvwrappb.WatchRequest
	(*WatchEventMessage)(nil),        // 10: kvwrappb.WatchEventMessage
}
var file_kv_proto_depIdxs = []int32{
	0,  // 0: kvwrappb.WatchEventMessage.event_type:type_name -> kvwrappb.WatchEventMessage.EventType
	1,  // 1: kvwrappb.KvService.Get:input_type -> kvwrappb.GetRequest
	3,  // 2: kvwrappb.KvService.Set:input_type -> kvwrappb.SetRequest
	5,  // 3: kvwrappb.KvService.Delete:input_type -> kvwrappb.DeleteRequest
	7,  // 4: kvwrappb.KvService.AllKeys:input_type -> kvwrappb.AllKeysRequest
	9,  // 5: kvwrappb.KvService.Watch:input_type -> kvwrappb.WatchRequest
	2,  // 6: kvwrappb.KvService.Get:output_type -> kvwrappb.GetResponse
	4,  // 7: kvwrappb.KvService.Set:output_type -> kvwrappb.SetResponse
	6,  // 8: kvwrappb.KvService.Delete:output_type -> kvwrappb.DeleteResponse
	8,  // 9: kvwrappb.KvService.AllKeys:output_type -> kvwrappb.AllKeysResponse
	10, // 10: kvwrappb.KvService.Watch:output_type -> kvwrappb.WatchEventMessage
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	file_kv_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
